### ISSUE TITLE
Inactive devices not showing on Spotify Connect menu

### ISSUE THREAD

**Issue by amd64fox** [jwty/Matcha-Spotify-Theme#1]
Dark theme does not show inactive devices on Spotify Connect menu.
![Без имен32423и](https://user-images.githubusercontent.com/62529699/111416683-72703d80-86f5-11eb-94f6-f6bf668ad511.png)

**Comment by jwty** [comment]
Hi, I can't seem to reproduce this issue (tested on Windows and Linux machines). Could you check if it persists in Light theme or with default Spotify theme?

![image](https://user-images.githubusercontent.com/24990977/111766696-21537b80-88a6-11eb-81cf-262e38b46c48.png)

**Comment by amd64fox** [comment]
> Could you check if it persists in Light theme or with default Spotify theme?

Light 
![Без 2222](https://user-images.githubusercontent.com/62529699/111776984-b4e77500-88c3-11eb-8bb0-ec2317ae5e6a.jpg)

Default 
![Без и676мени](https://user-images.githubusercontent.com/62529699/111777928-fd536280-88c4-11eb-9fba-7d86f4d8c816.jpg)
